# Numpy Assignment

## Problem Statement:1 Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

In [29]:
import numpy as np
def powers(a,num):
    output=np.column_stack([a**(num-i-1) for i in range(num)])
    return output

In [31]:
powers(a=np.array([1,2,3,4,5]),num=5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

## Problem Statement 2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below..................

In [33]:
a=[10,20,30,40,50,60,70,80,90,100]

In [24]:
summation=np.cumsum(a)
summation

array([ 10,  30,  60, 100, 150, 210, 280, 360, 450, 550], dtype=int32)

In [25]:
summation[n:]

array([100, 150, 210, 280, 360, 450, 550], dtype=int32)

In [10]:
summation[:-n]

array([  3,   8,  15,  17,  25,  35,  46, 111, 183, 264], dtype=int32)

In [26]:
summation[n:]=summation[n:]-summation[:-n]
summation[n:]

array([ 90, 120, 150, 180, 210, 240, 270], dtype=int32)

In [37]:
def moving(a, n=4):
    summation=np.cumsum(a, dtype=float)
    summation[n:]=summation[n:]-summation[:-n]
    return summation[n-1:]/n

In [38]:
moving(a=[10,20,30,40,50,60,70,80,90,100])


array([25., 35., 45., 55., 65., 75., 85.])

In [40]:
moving(a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], n=3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])